project:
  type: website
  output-dir: docs

website:
  title: "GISC 6302 - Fall 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu:
          - href: assign02.qmd
            text: Assignment 2
        menu:
          - href: assign03.qmd
            text: Assignment 3            

format:
  html:
    theme: cosmo
    toc: true

editor: visual