project:
  type: website

website:
  title: "GISC 6302 - Fall 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu:
          - href: assign02.qmd
            text: Assignment 2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual